server:
  port: 8002
  #context-path: /springcloud-provider
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver        #配置mysql的驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db_2?useSSL=false        #数据库连接地址
    username: root                                  #用户名
    password: password                              #密码
    filters: stat,wall,log4j
    dbcp2:                                          #数据库连接池的配置
      min-idle: 10                                  #数据库连接池最小维持连接数
      initial-size: 10                              #初始化提供的连接数
      max-total: 10                                 #最大连接数
      max-wait-millis: 200                          #等待连接获取的最大超时时间
      
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis 配置文件路径
  type-aliases-package: com.microcloud.api.bean             #定义所有操作类的别名所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml                  #所有的mapper映射文件
  
#security:
#  basic:
#    enabled: true                                   #启用springsecurity安全配置项
#  user:
#    name: springcloud                               #认证用户名
#    password: 123                                   #认证用户密码
#    role:                                           #用户角色
#    - USER
#  sessions: STATELESS                                  #session信息配置  ALWAYS（总是保存）   STATELESS（不保存，最好设置为不保存）


eureka:
  client: #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://springcloud:123@localhost:7001/eureka,http://springcloud:123@localhost:7002/eureka,http://springcloud:123@localhost:7003/eureka

  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #若超过5秒表示服务已经宕机了（默认是90秒）
    instance-id: dept-8002.com #在信息列表中显示主机名
    prefer-ip-address: true #访问的路径为IP地址
    
info: 
  app.name: springcloud
  company.name: www.dept.8002.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$