server:
  port: 80
  context-path: /springcloud-consumer-feign
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://springcloud:123@localhost:7001/eureka,
        http://springcloud:123@localhost:7002/eureka,
        http://springcloud:123@localhost:7003/eureka
        
feign:
  compression:
    request:
      mime-types: #可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 #超过2048字节进行压缩
logging: #feign 接口相关的日志信息（默认不开启）
  level:
    com.microcloud.service: DEBUG