server:
  port: 7002

spring:
  application:
    name: eureka-7002

eureka:
  server:
    enable-self-preservation: true #表示关闭保护模式
    eviction-interval-timer-in-ms: 1000 #设置清理时间间隔，这个时间是毫秒（默认是60秒）
  instance:  #eureka实例定义
    hostname: localhost:7002 #定义eureka实例所在的主机名称 
  client:
    service-url:
      defaultZone: http://springcloud:123@localhost:7001/eureka/,http://springcloud:123@localhost:7003/eureka/
    register-with-eureka: false #当前的服务不注册到eureka之中
    fetch-registry: false #不通过eureka获取注册信息
info: 
  app.name: springcloud
  company.name: www.eureka.7002.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  
  
security:
  basic:
    enabled: true #启用安全认证处理
  user:
    name: springcloud #用户名
    password: 123 #密码