spring:
  profiles:
    active:
    - dev-7001
---
spring:
  profiles: dev-7001
  application: 
    name: microcloud-eureka-7001
server:
  port: 7001
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: springcloud     # 用户名
    password: 123  # 密码
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://springcloud:123@localhost:7002/eureka,http://springcloud:123@localhost:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称
---
spring:
  profiles: dev-7002
  application: 
    name: microcloud-eureka-7002
server:
  port: 7002
security: 
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: springcloud     # 用户名
    password: 123  # 密码
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://springcloud:123@localhost:7001/eureka,http://springcloud:123@localhost:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7002.com # 定义Eureka实例所在的主机名称
---
spring:
  profiles: dev-7003
  application:
    name: microcloud-eureka-7003
server:
  port: 7003
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: springcloud     # 用户名
    password: 123  # 密码
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://springcloud:123@localhost:7001/eureka,http://springcloud:123@localhost:7002/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7003.com # 定义Eureka实例所在的主机名称
